### ISSUE TITLE
Help, how can I set gif-soup for dual-monitor setup?

### ISSUE THREAD

**Issue by MiraiMindz** [moviuro/moviuro.bin#2]
Hi, I have 2 monitors ( 1: 1366x786  |  2: 1280x1024) and i want to set a gif as my wallpaper, i am on ArchLinux with i3-WM

When I ran it I get one HUGE image instead of an image for each screen

What I have:
![Screenshot_20210816_192813](https://user-images.githubusercontent.com/78761663/129637429-5c76cd73-62a9-4561-8361-d17602ef73fe.png)

What was supposed to be:
![Screenshot_20210816_192535-1](https://user-images.githubusercontent.com/78761663/129637435-5c7b7dfe-2fa2-4275-acbd-4603530fdfae.png)

I read on the file that he uses Convert, but I cant find any convert package on the AUR, I have ImageMagick installed here, I don't know if magick is the "Convert" that he uses

when i run the script i get this output:
`convert: geometry does not contain image /home/mirai/GIFS/869910.gif @ warning/transform.c/CropImage/594.`

can you please help me?

EDIT = Found the solution, cropping the gifs and running two instances

**Comment by moviuro** [comment]
> Found the solution, cropping the gifs and running two instances

oh wow, that's cool. I'm surprised the two instances don't actually compete for the root window in Xorg?..!

Care to elaborate for the next people who will need it?
